### PR TITLE
Update build and docs

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Updated outdated build 
Fixed microsite icon
Updated documentation

### CODE REVIEW

**Comment by javipacheco** [comment]
Hey @AdrianRaFo 

Thank you for your contribution, but we shouldn't change the `organization` and `organizationName` to 47deg, for now, we should keep `macroid` here

On the other hand, this is a really huge PR, maybe we should create 2 differents PR:  one of them for updating build and docs and another with formatting (scalafmt). 
 
Thanks 👍

**Comment by AdrianRaFo** [comment]
@fedefernandez can you take a look? thanks

**Comment by fedefernandez** [comment]
@AdrianRaFo some conflicts have been appeared after merging #110. Please, could you resolve them? Thanks

**Comment by fedefernandez** [comment]
I'm going to revert #110 and merge this first.

**Pull request merged**
